<a href="https://colab.research.google.com/github/sarada-atluri/ML-Using-pandas/blob/main/Working_with_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
# mount the drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#read file from the drive
import pandas as pd

In [4]:
datasetpath = '/content/drive/MyDrive/Document from Sarada'

In [5]:
df = pd.read_csv(datasetpath)

In [6]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [7]:
df.describe()

          StoreID   CustomerID   ProductID    Quantity      Price   Discount
count  100.000000   100.000000  100.000000  100.000000  100.00000  75.000000
mean   102.730000  1552.520000  554.390000    5.370000  282.15000   7.733333
std      1.384291   268.295461   28.544098    3.013957  140.19938   5.652871
min    101.000000  1013.000000  501.000000    1.000000   50.00000   0.000000
25%    101.000000  1310.250000  529.750000    3.000000  165.75000   2.500000
50%    103.000000  1534.000000  554.000000    5.500000  280.00000  10.000000
75%    104.000000  1800.750000  579.500000    8.000000  415.25000  12.500000
max    105.000000  1983.000000  600.000000   10.000000  500.00000  15.000000

In [8]:
df.head(15)

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
5,T006,2024-01-06,103,1836,515,Grocery,9,227,Debit,NaN
6,T007,2024-01-07,103,1983,586,Electronics,1,170,Credit,NaN
7,T008,2024-01-08,101,1806,569,Toys,4,500,Debit,0.0
8,T009,2024-01-09,101,1925,548,Apparel,7,217,Cash,10.0
9,T010,2024-01-10,101,1711,565,Furniture,3,466,Debit,5.0
10,T011,2024-01-11,103,1276,565,Furniture,1,321,Cash,NaN
11,T012,2024-01-12,101,1486,523,Toys,8,426,Credit,5.0
12,T013,2024-01-13,103,1597,516,Toys,5,262,Cash,15.0
13,T014,2024-01-14,101,1462,520,Electronics,10,218,Cash,NaN
14,T015,2024-01-15,104,1668,581,Toys,4,201,Debit,15.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    100 non-null    object
 1   TransactionDate  100 non-null    object
 2   StoreID          100 non-null    int64
 3   CustomerID       100 non-null    int64
 4   ProductID        100 non-null    int64
 5   ProductCategory  100 non-null    object
 6   Quantity         100 non-null    int64
 7   Price            100 non-null    int64
 8   PaymentType      100 non-null    object
 9   Discount         75 non-null     float64
dtypes: float64(1), int64(5), object(4)
memory usage: 7.9+ KB

In [10]:
missing_values = df.isnull().sum()

In [11]:
print(missing_values)

TransactionID       0
TransactionDate     0
StoreID             0
CustomerID          0
ProductID           0
ProductCategory     0
Quantity            0
Price               0
PaymentType         0
Discount           25
dtype: int64

In [12]:
df["Quantity"] = pd.to_numeric(df["Quantity"],errors="coerce")
df["Price"] = pd.to_numeric(df["Price"],errors="coerce")
df["Discount"] = pd.to_numeric(df["Discount"],errors="coerce")

In [13]:
df.dtypes

TransactionID       object
TransactionDate     object
StoreID              int64
CustomerID           int64
ProductID            int64
ProductCategory     object
Quantity             int64
Price                int64
PaymentType         object
Discount           float64
dtype: object

In [15]:
(df)

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [17]:
df['NetPrice'] = df['Price'] * (1-df['Discount'])

In [18]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,-2100.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,-2853.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,-4464.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.0
...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,-3951.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,-1359.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,-4311.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,-3458.0

In [19]:
df['TotalSale'] = df['Quantity'] * df['NetPrice']

In [20]:
filtered_df = df[df['TotalSale'] >=20]

In [21]:
filtered_df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.0,1660.0
7,T008,2024-01-08,101,1806,569,Toys,4,500,Debit,0.0,500.0,2000.0
15,T016,2024-01-16,101,1278,594,Toys,8,416,Credit,0.0,416.0,3328.0
17,T018,2024-01-18,102,1199,565,Apparel,6,495,Credit,0.0,495.0,2970.0
18,T019,2024-01-19,101,1734,599,Apparel,9,55,Debit,0.0,55.0,495.0
24,T025,2024-01-25,103,1928,578,Toys,2,185,Cash,0.0,185.0,370.0
30,T031,2024-01-31,101,1922,576,Toys,2,333,Cash,0.0,333.0,666.0
34,T035,2024-02-04,101,1135,536,Electronics,1,157,Credit,0.0,157.0,157.0
47,T048,2024-02-17,103,1385,599,Toys,3,495,Credit,0.0,495.0,1485.0
53,T054,2024-02-23,105,1293,579,Toys,8,402,Cash,0.0,402.0,3216.0
55,T056,2024-02-25,105,1263,549,Apparel,6,166,Cash,0.0,166.0,996.0
58,T059,2024-02-28,102,1536,546,Electronics,5,50,Credit,0.0,50.0,250.0
66,T067,2024-03-07,103,1308,523,Apparel,7,60,Cash,0.0,60.0,420.0
69,T070,2024-03-10,105,1954,516,Grocery,9,109,Credit,0.0,109.0,981.0
71,T072,2024-03-12,104,1236,587,Apparel,1,494,Debit,0.0,494.0,494.0
72,T073,2024-03-13,103,1798,530,Furniture,2,59,Cash,0.0,59.0,118.0
78,T079,2024-03-19,101,1821,575,Apparel,6,480,Debit,0.0,480.0,2880.0
84,T085,2024-03-25,105,1326,553,Grocery,9,149,Debit,0.0,149.0,1341.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.0,208.0

In [22]:
filterd_df = df[df['TotalSale'] >=20].copy()

In [23]:
filtered_df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.0,1660.0
7,T008,2024-01-08,101,1806,569,Toys,4,500,Debit,0.0,500.0,2000.0
15,T016,2024-01-16,101,1278,594,Toys,8,416,Credit,0.0,416.0,3328.0
17,T018,2024-01-18,102,1199,565,Apparel,6,495,Credit,0.0,495.0,2970.0
18,T019,2024-01-19,101,1734,599,Apparel,9,55,Debit,0.0,55.0,495.0
24,T025,2024-01-25,103,1928,578,Toys,2,185,Cash,0.0,185.0,370.0
30,T031,2024-01-31,101,1922,576,Toys,2,333,Cash,0.0,333.0,666.0
34,T035,2024-02-04,101,1135,536,Electronics,1,157,Credit,0.0,157.0,157.0
47,T048,2024-02-17,103,1385,599,Toys,3,495,Credit,0.0,495.0,1485.0
53,T054,2024-02-23,105,1293,579,Toys,8,402,Cash,0.0,402.0,3216.0
55,T056,2024-02-25,105,1263,549,Apparel,6,166,Cash,0.0,166.0,996.0
58,T059,2024-02-28,102,1536,546,Electronics,5,50,Credit,0.0,50.0,250.0
66,T067,2024-03-07,103,1308,523,Apparel,7,60,Cash,0.0,60.0,420.0
69,T070,2024-03-10,105,1954,516,Grocery,9,109,Credit,0.0,109.0,981.0
71,T072,2024-03-12,104,1236,587,Apparel,1,494,Debit,0.0,494.0,494.0
72,T073,2024-03-13,103,1798,530,Furniture,2,59,Cash,0.0,59.0,118.0
78,T079,2024-03-19,101,1821,575,Apparel,6,480,Debit,0.0,480.0,2880.0
84,T085,2024-03-25,105,1326,553,Grocery,9,149,Debit,0.0,149.0,1341.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.0,208.0

In [24]:

if 'Payment_Type' in df.columns:
    df['Payment_Type'] = df['Payment_Type'].astype('category')

In [25]:
df.dtypes

TransactionID       object
TransactionDate     object
StoreID              int64
CustomerID           int64
ProductID            int64
ProductCategory     object
Quantity             int64
Price                int64
PaymentType         object
Discount           float64
NetPrice           float64
TotalSale          float64
dtype: object

In [29]:

grouped_df = df.groupby('ProductCategory').agg(
      TotalQuantity = ('Quantity','sum'),
      TotalSales = ('TotalSale','sum')
)

In [30]:
sorted_df = grouped_df.sort_values(by = 'TotalSales', ascending= False)

In [31]:
top_3_categories = sorted_df.head()

In [32]:
top_3_categories

                 TotalQuantity  TotalSales
ProductCategory
Electronics                 78    -71161.0
Grocery                     75   -127533.0
Apparel                    117   -165434.0
Furniture                  130   -210155.0
Toys                       137   -235513.0

In [34]:

grouped_df = df.groupby(['StoreID','ProductCategory']).agg(
    AvgTotalSale = ('TotalSale','mean')
).reset_index()

In [35]:
top_category_df = grouped_df.loc[grouped_df.groupby('StoreID')['AvgTotalSale'].idxmax()]

In [36]:
top_category_df.rename(columns={'ProductCategory':'reProductCategory'}, inplace=True)

In [37]:
top_category_df

    StoreID reProductCategory  AvgTotalSale
0       101           Apparel  -6323.000000
7       102           Grocery  -1719.000000
12      103           Grocery  -5598.666667
14      104           Apparel  -1753.000000
23      105              Toys   3216.000000